# Generated by Django 3.1.2 on 2020-11-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipToAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('index', models.CharField(max_length=6)),
                ('telephone', models.CharField(max_length=11)),
                ('contactPersonPhoneNumber', models.CharField(blank=True, max_length=11)),
                ('contactPersonEmail', models.CharField(blank=True, max_length=50)),
                ('shipToAddresses', models.ManyToManyField(blank=True, related_name='customers', to='COC.ShipToAddress')),
            ],
        ),
    ]
