# Generated by Django 3.1.2 on 2020-11-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shipToAddresses',
        ),
        migrations.DeleteModel(
            name='ShipToAddress',
        ),
    ]
