# Generated by Django 3.1.2 on 2020-11-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COC', '0003_auto_20201105_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('denomination', models.CharField(db_index=True, max_length=150)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroupDiscount',
            fields=[
                ('price_group', models.CharField(db_index=True, max_length=150)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('denomination', models.CharField(db_index=True, max_length=150)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('box_quantity', models.IntegerField()),
                ('min_order_quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COC.pricegroup')),
            ],
        ),
    ]
