# Generated by Django 3.1.2 on 2020-11-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COC', '0004_pricegroup_pricegroupdiscount_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='COC.pricegroup'),
        ),
    ]
