# Generated by Django 3.1.2 on 2020-11-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COC', '0006_auto_20201105_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_group_discounts',
            field=models.ManyToManyField(blank=True, to='COC.PriceGroupDiscount'),
        ),
    ]
