# Generated by Django 3.1.2 on 2020-11-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COC', '0008_commercialoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialoffer',
            name='products',
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='products',
            field=models.ManyToManyField(blank=True, to='COC.Product'),
        ),
    ]
